name: "Personal Agent Plugin"

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"

jobs:
  compute:
    name: "Personal Agent Plugin"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: install dependencies
        run: yarn

      - name: execute directive
        run: npx tsx ./src/main.ts
        id: plugin-personal-agent
        env:
          PERSONAL_AGENT_PAT_CLASSIC: ${{ secrets.PERSONAL_AGENT_PAT_CLASSIC }}
